version: '3'

services:
  backend-url-shrotener:
    container_name: backend
    build: 
      context: ../url-shortener
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - "db-url-shorterner"
    networks:
      - "url-shortener-network"

  db-url-shorterner:
    container_name: db
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - .:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - "url-shortener-network"

networks:
    url-shortener-network:
        driver: bridge